import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";

import { config } from "@/config";
import "./globals.css";
import ServerProvider from "./components/ServerProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const initialState = cookieToInitialState(config, headers().get("cookie"));

	return (
		<html lang="en">
			<body className={inter.className}>
				<ServerProvider initialState={initialState}>
					<ThemeProvider defaultTheme="dark" attribute="class">
						{children}
					</ThemeProvider>
				</ServerProvider>
			</body>
		</html>
	);
}
