import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { WagmiProvider } from "wagmi";
import { config } from "@/config";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const queryClient = new QueryClient()

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<WagmiProvider config={config}>
					<QueryClientProvider client={queryClient}>
						<ThemeProvider defaultTheme="dark" attribute="class">
							{children}
						</ThemeProvider>
					</QueryClientProvider>
				</WagmiProvider>
			</body>
		</html>
	);
}
